name: Test

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - "macos-12"
          - "ubuntu-20.04"
#          - windows-2022

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: npm install
        run: |
          npm install

      - name: npm test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run package
          npm run lint
          npm run test

# Failing beacuse virtual framebuffer not installed
#          npm run build-e2e
#          npm test-e2e
